const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const puppeteer=require(process.env.PUPPETEER_MODULE||'puppeteer-core');
(async()=>{
 const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-sandbox']});
 try {
 const page=await browser.newPage(); const errors=[],failed=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push([r.url(),r.status()]);});
 await page.setViewport({width:390,height:844,isMobile:true,deviceScaleFactor:1});
 await page.evaluateOnNewDocument(()=>{window.interactions=[];new PerformanceObserver(list=>{for(const e of list.getEntries())if(e.interactionId)window.interactions.push({duration:e.duration,type:e.name});}).observe({type:'event',buffered:true,durationThreshold:16});});
 await page.goto(process.env.TEST_URL||'http://127.0.0.1:8767/',{waitUntil:'networkidle0'});
 await page.waitForFunction(()=>document.querySelectorAll('.nbx-card-actions').length===20);
 assert.equal(await page.$eval('link[rel=canonical]',e=>e.href),'https://name.ilmualam.com/');
 assert.equal(await page.$$eval('h1',e=>e.length),1);
 await page.click('[data-gender="P"]');
 assert.equal(await page.$eval('[data-gender="P"]',e=>e.getAttribute('aria-pressed')),'true');
 await page.type('#nbxSearch','Maryam');await new Promise(r=>setTimeout(r,400));
 assert.ok(await page.$$eval('.nbx-card',els=>els.length>0&&els.every(e=>e.textContent.toLowerCase().includes('maryam'))));
 await page.click('.nbx-btn-save');
 assert.equal(await page.$eval('#statSaved',e=>e.textContent),'1');
 await page.reload({waitUntil:'networkidle0'});
 assert.equal(await page.$eval('#statSaved',e=>e.textContent),'1');
 await page.click('.nbx-shortlist-remove');
 assert.equal(await page.$eval('#statSaved',e=>e.textContent),'0');
 await page.click('[data-gender="ALL"]');
 await page.focus('#nbxCombine1');
 const vals=await page.$$eval('#nbxCombine1 option',opts=>[...new Set(opts.map(e=>e.value).filter(Boolean))].slice(0,2));
 await page.select('#nbxCombine1',vals[0]);await page.select('#nbxCombine2',vals[1]);await page.click('.nbx-combine-btn');
 assert.equal(await page.$eval('#nbxCombineName',e=>e.textContent),vals.join(' '));
 await page.select('#nbxHuruf','Z');
 assert.ok(await page.$$eval('.nbx-card-name',els=>els.length>0&&els.every(e=>e.textContent.startsWith('Z'))));
 await page.click('.nbx-clear-btn');
 await page.click('.nbx-chip:nth-child(2)');
 assert.equal(await page.$eval('.nbx-chip:nth-child(2)',e=>e.getAttribute('aria-pressed')),'true');
 await page.click('.nbx-clear-btn');
 await page.click('[aria-label="Halaman seterusnya"]');
 assert.ok(await page.$$eval('.nbx-page-info',els=>els.some(e=>e.textContent.includes('2 /'))));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const metrics=await page.evaluate(()=>{const n=performance.getEntriesByType('navigation')[0];return {localTTFB:n.responseStart-n.startTime,observedInteractionMax:Math.max(0,...window.interactions.map(e=>e.duration)),interactionEvents:window.interactions.length};});
 if(process.env.SCREENSHOT_PATH)await page.screenshot({path:process.env.SCREENSHOT_PATH,fullPage:true});
 await page.setJavaScriptEnabled(false);await page.reload({waitUntil:'networkidle0'});
 assert.equal(await page.$$eval('.nbx-card',els=>els.length),20);
 assert.ok(await page.$eval('#faq',e=>e.textContent.includes('Tidak.')));
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 console.log('PASS search, gender, letter, theme, pagination, shortlist persistence/removal, combiner, no-JS examples, mobile overflow and console/network checks.');
 console.log(JSON.stringify(metrics));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
