const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const puppeteer=require(process.env.PUPPETEER_MODULE||'puppeteer-core');
const root=path.resolve(__dirname,'..'),read=name=>fs.readFileSync(path.join(root,name));let worker=read('sw.js').toString();let offline=false;
const server=http.createServer((req,res)=>{if(offline){req.socket.destroy();return;}const url=new URL(req.url,'http://localhost');const name=url.pathname==='/'?'index.html':url.pathname.slice(1);const file=path.resolve(root,name);if(req.method!=='GET'){res.writeHead(405);return res.end();}try{assert.ok(file.startsWith(root+path.sep));const body=name==='sw.js'?worker:fs.readFileSync(file);res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)]||'text/plain','Cache-Control':'no-store'});res.end(body);}catch{res.writeHead(404,{'Content-Type':'text/html'});res.end(read('404.html'));}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;let browser;try{
browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-sandbox']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.evaluateOnNewDocument(()=>sessionStorage.setItem('loads',String(Number(sessionStorage.getItem('loads')||0)+1)));
await page.goto(origin,{waitUntil:'networkidle0'});await page.waitForFunction(()=>!!navigator.serviceWorker.controller);assert.equal(await page.evaluate(()=>sessionStorage.getItem('loads')),'1');const cdp=await page.createCDPSession();assert.equal((await cdp.send('Page.getAppManifest')).errors.length,0);assert.equal((await cdp.send('Page.getInstallabilityErrors')).installabilityErrors.length,0);
const cached=await page.evaluate(async()=>{const key=(await caches.keys()).find(k=>k.startsWith('ilmu-name-'));return(await(await caches.open(key)).keys()).map(r=>new URL(r.url).pathname);});assert.deepEqual(cached.sort(),JSON.parse(worker.match(/const PRECACHE=(\[[^;]+\]);/)[1]).sort());
offline=true;await page.setOfflineMode(true);await page.reload({waitUntil:'networkidle0'});await page.waitForFunction(()=>document.querySelectorAll('.nbx-card-actions').length===20);await page.click('[data-gender="P"]');await page.type('#nbxSearch','Maryam');await new Promise(r=>setTimeout(r,400));assert.ok(await page.$$eval('.nbx-card',els=>els.length>0&&els.every(e=>e.textContent.toLowerCase().includes('maryam'))));await page.click('.nbx-btn-save');assert.equal(await page.$eval('#statSaved',e=>e.textContent),'1');await page.reload({waitUntil:'networkidle0'});await page.waitForFunction(()=>document.getElementById('statSaved').textContent==='1');await page.focus('#nbxCombine1');const names=await page.$$eval('#nbxCombine1 option',els=>els.map(e=>e.value).filter(Boolean).slice(0,2));await page.select('#nbxCombine1',names[0]);await page.select('#nbxCombine2',names[1]);await page.click('.nbx-combine-btn');assert.equal(await page.$eval('#nbxCombineName',e=>e.textContent),names.join(' '));
assert.equal((await page.goto(origin+'/asset/index.html',{waitUntil:'networkidle0'})).status(),200);assert.equal((await page.goto(origin+'/unavailable',{waitUntil:'networkidle0'})).status(),503);await page.goto(origin,{waitUntil:'networkidle0'});
offline=false;await page.setOfflineMode(false);await page.evaluate(async()=>{await(await caches.open('other-app-cache')).put('/unrelated',new Response('keep'));await(await caches.open('ilmu-name-obsolete')).put('/old',new Response('old'));});worker=worker.replace(/const CACHE=PREFIX\+'[^']+';/,"const CACHE=PREFIX+'test-updated';");await page.evaluate(async()=>await(await navigator.serviceWorker.getRegistration()).update());await page.waitForFunction(async()=>!!(await navigator.serviceWorker.getRegistration()).waiting,{timeout:20000});assert.equal(await page.evaluate(()=>!!navigator.serviceWorker.controller),true);await page.waitForFunction(()=>!document.getElementById('pwaUpdate').hidden);const before=await page.evaluate(()=>Number(sessionStorage.getItem('loads')));await Promise.all([page.waitForNavigation({waitUntil:'networkidle0'}),page.click('#pwaUpdate')]);assert.equal(await page.evaluate(()=>Number(sessionStorage.getItem('loads'))),before+1);assert.ok(await page.evaluate(async()=>{const keys=await caches.keys();return keys.includes('other-app-cache')&&!keys.includes('ilmu-name-obsolete')&&keys.includes('ilmu-name-test-updated');}));assert.equal((await page.goto(origin+'/unknown',{waitUntil:'networkidle0'})).status(),404);await page.goto(origin,{waitUntil:'networkidle0'});assert.equal(await page.evaluate(async()=> (await fetch('/api-test',{method:'POST',body:'test'})).status),405);assert.deepEqual(errors,[]);
console.log('PASS manifest/installability, complete cache, offline search/filter/save/combine, alias navigation, offline 503, online 404, POST bypass, consented update and scoped cache cleanup.');
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
